### PR TITLE
Updating readme and AnnotationVideoRenderer to avoid NPEs on startup/layout

### PR DESCRIPTION
**Pull request by diego-tw**
Hi, a small change to avoid NPEs during setup. With this change, the HelloWorld with annotations (as directed by the ReadMe) did not crash during setup, I hope it's the right approach, though.

### CODE REVIEW

**Comment by trevordboyer** [comment]
Thanks! I'll take a closer look at these, but that looks like it should be fine.

**Comment by marinaserranomontes** [comment]
@diego-tw thanks for your comments. Regarding your changes, please note the following:
- Doc has been update. You have to set the renderer before to start/stop publishing. And you don't need to setLayoutParams..
- Good catch about checking if frame is null before to try to get the width/height.
- .gitignore file has been uploaded following the template we use for all the android project.

Please, could you review the last changes? And if you have some other comments, let us know. Thank you so much

**Comment by diego-tw** [comment]
Hi Marina, thanks very much for your response !

I set the renderer in the attachPublisherView() which is before starting
the publishing - but you're right, no need to set the layout, hooray.

We are trying to get the annotations working but they do not seem to be
displayed on the subscriber sides. I presume that whatever is drawn on a
publisher view should be transmitted (via signals ?) and shown to all
subscribers ?

Actually, would you happen to have a working example of what annotations
can do at this stage ?
If so, would you be able to share this via GitHub ? This may be the easiest
path for users to explore the new feature, rather than having to bother
your team with questions ?

Kind regards,
Diego

Diego Tognola
N00b Tech Principle
Email dtognola@thoughtworks.com
Telephone +61 4 1753 8161 <+61+4+1753+8161>
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=diego-tognola-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>

**Comment by marinaserranomontes** [comment]
@diego-tw as we have commented the changes by email, and updated them, let me close this PR. Thanks!!

**Pull request closed without merging**
